### ISSUE TITLE
CRUD employee

### ISSUE THREAD

**Issue by nicolasbalao** [nicolasbalao/AgroConnect#4]
# Use cases
- [x] Create an employe with relation
- [x] Update an employe with relation
- [x] Delete an employe 
- [x] Liste all employe
- [x] Search employe by latname, firstname, name of site, name of department

## Plus
- [x] Implement pagination

**Comment by nicolasbalao** [comment]
## Pagination system

**Request params**
- page
- size

**Data needed for pagination process**
- page
- limit
- size
- offset = (page - 1) * size

**Response request body**
- totalItem = total of employee
- Items = employee
- page = current page
- size = number of employee returned

### To-do

**Decorator for extract pagination params**
- [ ] Extract param for the url 
- [ ] Validation of params
- [ ] Contruction of _data needed for pagination process_

**Db request**
- [ ]  Take 
- [ ]  Skip
- [ ] Count
